//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsumidorWS.CalculadoraWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCalculadora1Soap", Namespace="http://tempuri.org/")]
    public partial class WSCalculadora1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CalculadoraOperationCompleted;
        
        private System.Threading.SendOrPostCallback FatorialOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImcOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConversaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCalculadora1() {
            this.Url = global::ConsumidorWS.Properties.Settings.Default.ConsumidorWS_CalculadoraWS_WSCalculadora1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CalculadoraCompletedEventHandler CalculadoraCompleted;
        
        /// <remarks/>
        public event FatorialCompletedEventHandler FatorialCompleted;
        
        /// <remarks/>
        public event ImcCompletedEventHandler ImcCompleted;
        
        /// <remarks/>
        public event ConversaoCompletedEventHandler ConversaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Calculadora", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Calculadora(float v1, float v2, char op) {
            object[] results = this.Invoke("Calculadora", new object[] {
                        v1,
                        v2,
                        op});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CalculadoraAsync(float v1, float v2, char op) {
            this.CalculadoraAsync(v1, v2, op, null);
        }
        
        /// <remarks/>
        public void CalculadoraAsync(float v1, float v2, char op, object userState) {
            if ((this.CalculadoraOperationCompleted == null)) {
                this.CalculadoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculadoraOperationCompleted);
            }
            this.InvokeAsync("Calculadora", new object[] {
                        v1,
                        v2,
                        op}, this.CalculadoraOperationCompleted, userState);
        }
        
        private void OnCalculadoraOperationCompleted(object arg) {
            if ((this.CalculadoraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculadoraCompleted(this, new CalculadoraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Fatorial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Fatorial(int v1) {
            object[] results = this.Invoke("Fatorial", new object[] {
                        v1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FatorialAsync(int v1) {
            this.FatorialAsync(v1, null);
        }
        
        /// <remarks/>
        public void FatorialAsync(int v1, object userState) {
            if ((this.FatorialOperationCompleted == null)) {
                this.FatorialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFatorialOperationCompleted);
            }
            this.InvokeAsync("Fatorial", new object[] {
                        v1}, this.FatorialOperationCompleted, userState);
        }
        
        private void OnFatorialOperationCompleted(object arg) {
            if ((this.FatorialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FatorialCompleted(this, new FatorialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Imc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Imc(float altura, float peso) {
            object[] results = this.Invoke("Imc", new object[] {
                        altura,
                        peso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImcAsync(float altura, float peso) {
            this.ImcAsync(altura, peso, null);
        }
        
        /// <remarks/>
        public void ImcAsync(float altura, float peso, object userState) {
            if ((this.ImcOperationCompleted == null)) {
                this.ImcOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImcOperationCompleted);
            }
            this.InvokeAsync("Imc", new object[] {
                        altura,
                        peso}, this.ImcOperationCompleted, userState);
        }
        
        private void OnImcOperationCompleted(object arg) {
            if ((this.ImcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImcCompleted(this, new ImcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Conversao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float Conversao(float valorMetros, string tipoMedida) {
            object[] results = this.Invoke("Conversao", new object[] {
                        valorMetros,
                        tipoMedida});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void ConversaoAsync(float valorMetros, string tipoMedida) {
            this.ConversaoAsync(valorMetros, tipoMedida, null);
        }
        
        /// <remarks/>
        public void ConversaoAsync(float valorMetros, string tipoMedida, object userState) {
            if ((this.ConversaoOperationCompleted == null)) {
                this.ConversaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConversaoOperationCompleted);
            }
            this.InvokeAsync("Conversao", new object[] {
                        valorMetros,
                        tipoMedida}, this.ConversaoOperationCompleted, userState);
        }
        
        private void OnConversaoOperationCompleted(object arg) {
            if ((this.ConversaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConversaoCompleted(this, new ConversaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CalculadoraCompletedEventHandler(object sender, CalculadoraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculadoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculadoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FatorialCompletedEventHandler(object sender, FatorialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FatorialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FatorialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ImcCompletedEventHandler(object sender, ImcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConversaoCompletedEventHandler(object sender, ConversaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConversaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConversaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591